// Generated by Apple Swift version 5.1 effective-4.2 (swiftlang-1100.0.270.13 clang-1100.0.33.7)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreGraphics;
@import Dispatch;
@import Foundation;
@import InputBarAccessoryView;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Channelize",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSCoder;
@class NSAttributedString;

SWIFT_CLASS("_TtC10Channelize19BottomSeparatorCell")
@interface BottomSeparatorCell : UICollectionViewCell
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)setTextOnLabel:(NSAttributedString * _Nonnull)text :(NSTextAlignment)alignment SWIFT_DEPRECATED_OBJC("Swift method 'BottomSeparatorCell.setTextOnLabel(_:_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)layoutSubviews;
@end

@class UITextView;

SWIFT_CLASS("_TtC10Channelize7CHToken")
@interface CHToken : UIView
@property (nonatomic, strong) UITextView * _Nonnull hiddenTextView SWIFT_DEPRECATED_OBJC("Swift property 'CHToken.hiddenTextView' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic) BOOL isSelected SWIFT_DEPRECATED_OBJC("Swift property 'CHToken.isSelected' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class UITapGestureRecognizer;

SWIFT_CLASS("_TtC10Channelize11CHTokenView")
@interface CHTokenView : UIView <UITextViewDelegate>
@property (nonatomic, strong) UITextView * _Nonnull textView SWIFT_DEPRECATED_OBJC("Swift property 'CHTokenView.textView' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)layoutSubviews;
- (void)awakeFromNib;
/// Reloads data from datasource and delegate implementations.
- (void)reloadData SWIFT_DEPRECATED_OBJC("Swift method 'CHTokenView.reloadData()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Returns a generated token.
/// \param index Int value for token index.
///
///
/// returns:
/// CHToken
- (CHToken * _Nonnull)tokenForIndex:(NSInteger)index SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'CHTokenView.tokenForIndex(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Selects the tapped token for interaction (i.e. removal).
/// \param tapGesture UITapGestureRecognizer associated with the token.
///
///
/// returns:
/// CHToken
- (void)didTapToken:(UITapGestureRecognizer * _Nonnull)tapGesture;
- (void)selectToken:(CHToken * _Nonnull)token SWIFT_DEPRECATED_OBJC("Swift method 'CHTokenView.selectToken(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)textViewDidBeginEditing:(UITextView * _Nonnull)textView;
- (void)textViewDidEndEditing:(UITextView * _Nonnull)textView;
- (BOOL)textView:(UITextView * _Nonnull)textView shouldChangeTextInRange:(NSRange)range replacementText:(NSString * _Nonnull)text SWIFT_WARN_UNUSED_RESULT;
- (void)textViewDidChange:(UITextView * _Nonnull)textView;
/// Dismiss keyboard and resign responder for Token View
- (void)dismissTokenView SWIFT_DEPRECATED_OBJC("Swift method 'CHTokenView.dismissTokenView()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC10Channelize11Cancellable")
@interface Cancellable : NSObject
@property (nonatomic, readonly) BOOL isCancelled SWIFT_DEPRECATED_OBJC("Swift property 'Cancellable.isCancelled' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)cancel SWIFT_DEPRECATED_OBJC("Swift method 'Cancellable.cancel()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface InputTextView (SWIFT_EXTENSION(Channelize)) <UITextViewDelegate>
- (BOOL)textView:(UITextView * _Nonnull)textView shouldChangeTextInRange:(NSRange)range replacementText:(NSString * _Nonnull)text SWIFT_WARN_UNUSED_RESULT;
@end







@class UICollectionViewLayout;
@class NSBundle;

SWIFT_CLASS("_TtC10Channelize23RecentMessageController")
@interface RecentMessageController : UICollectionViewController
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (nonnull instancetype)initWithCollectionViewLayout:(UICollectionViewLayout * _Nonnull)layout OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end





@class UICollectionView;

@interface RecentMessageController (SWIFT_EXTENSION(Channelize)) <UICollectionViewDelegateFlowLayout>
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumLineSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
@end


@interface RecentMessageController (SWIFT_EXTENSION(Channelize)) <UIGestureRecognizerDelegate>
@end

@class UISearchBar;

@interface RecentMessageController (SWIFT_EXTENSION(Channelize)) <UISearchBarDelegate>
- (BOOL)searchBarShouldBeginEditing:(UISearchBar * _Nonnull)searchBar SWIFT_WARN_UNUSED_RESULT;
@end

@class UIScrollView;

@interface RecentMessageController (SWIFT_EXTENSION(Channelize))
- (void)scrollViewWillBeginDragging:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDragging:(UIScrollView * _Nonnull)scrollView willDecelerate:(BOOL)decelerate;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewWillBeginDecelerating:(UIScrollView * _Nonnull)scrollView;
@end




@interface RecentMessageController (SWIFT_EXTENSION(Channelize))
- (void)didUserGetOnlineWithUserId:(NSString * _Nonnull)userId SWIFT_DEPRECATED_OBJC("Swift method 'RecentMessageController.didUserGetOnline(userId:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)didUserGetOfflineWithUserId:(NSString * _Nonnull)userId SWIFT_DEPRECATED_OBJC("Swift method 'RecentMessageController.didUserGetOffline(userId:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)didUserBlockedWithIsMe:(BOOL)isMe userId:(NSString * _Nullable)userId SWIFT_DEPRECATED_OBJC("Swift method 'RecentMessageController.didUserBlocked(isMe:userId:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end

@class UICollectionReusableView;

@interface RecentMessageController (SWIFT_EXTENSION(Channelize))
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout referenceSizeForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionReusableView * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView viewForSupplementaryElementOfKind:(NSString * _Nonnull)kind atIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface RecentMessageController (SWIFT_EXTENSION(Channelize))
- (void)didAdminAddedWithConversationId:(NSString * _Nullable)conversationId isAdmin:(BOOL)isAdmin userId:(NSString * _Nullable)userId SWIFT_DEPRECATED_OBJC("Swift method 'RecentMessageController.didAdminAdded(conversationId:isAdmin:userId:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)didChangeTypingStatusWithConversationId:(NSString * _Nullable)conversationId userId:(NSString * _Nullable)userId isTyping:(BOOL)isTyping SWIFT_DEPRECATED_OBJC("Swift method 'RecentMessageController.didChangeTypingStatus(conversationId:userId:isTyping:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)didMessagesDeletedForEveryOneWithConversationId:(NSString * _Nullable)conversationId messageIds:(NSArray<NSString *> * _Nullable)messageIds SWIFT_DEPRECATED_OBJC("Swift method 'RecentMessageController.didMessagesDeletedForEveryOne(conversationId:messageIds:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end

@class NSURLSession;
@class NSError;

SWIFT_CLASS("_TtC10Channelize16SwiftLinkPreview")
@interface SwiftLinkPreview : NSObject
@property (nonatomic, strong) NSURLSession * _Nonnull session SWIFT_DEPRECATED_OBJC("Swift property 'SwiftLinkPreview.session' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly, strong) dispatch_queue_t _Nonnull workQueue SWIFT_DEPRECATED_OBJC("Swift property 'SwiftLinkPreview.workQueue' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly, strong) dispatch_queue_t _Nonnull responseQueue SWIFT_DEPRECATED_OBJC("Swift property 'SwiftLinkPreview.responseQueue' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) dispatch_queue_t _Nonnull defaultWorkQueue SWIFT_DEPRECATED_OBJC("Swift property 'SwiftLinkPreview.defaultWorkQueue' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");)
+ (dispatch_queue_t _Nonnull)defaultWorkQueue SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift property 'SwiftLinkPreview.defaultWorkQueue' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithSession:(NSURLSession * _Nullable)session workQueue:(dispatch_queue_t _Nullable)workQueue responseQueue:(dispatch_queue_t _Nullable)responseQueue disableInMemoryCache:(BOOL)disableInMemoryCache cacheInvalidationTimeout:(NSTimeInterval)cacheInvalidationTimeout cacheCleanupInterval:(NSTimeInterval)cacheCleanupInterval OBJC_DESIGNATED_INITIALIZER;
- (Cancellable * _Nonnull)previewLink:(NSString * _Nonnull)text onSuccess:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nonnull))onSuccess onError:(void (^ _Nonnull)(NSError * _Nonnull))onError;
@end

@class NSURLSessionTask;
@class NSHTTPURLResponse;

@interface SwiftLinkPreview (SWIFT_EXTENSION(Channelize)) <NSURLSessionDataDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task willPerformHTTPRedirection:(NSHTTPURLResponse * _Nonnull)response newRequest:(NSURLRequest * _Nonnull)request completionHandler:(void (^ _Nonnull)(NSURLRequest * _Nullable))completionHandler;
@end


@interface SwiftLinkPreview (SWIFT_EXTENSION(Channelize))
- (NSURL * _Nullable)extractURLWithText:(NSString * _Nonnull)text SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'SwiftLinkPreview.extractURL(text:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end



@class UIFont;
@class UIColor;

SWIFT_CLASS("_TtC10Channelize18TTSegmentedControl")
@interface TTSegmentedControl : UIView
@property (nonatomic, strong) UIFont * _Nonnull defaultTextFont;
@property (nonatomic, strong) UIFont * _Nonnull selectedTextFont;
@property (nonatomic, strong) UIColor * _Nonnull defaultTextColor;
@property (nonatomic, strong) UIColor * _Nonnull selectedTextColor;
@property (nonatomic) BOOL useGradient;
@property (nonatomic, strong) UIColor * _Nonnull containerBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull thumbColor;
@property (nonatomic, copy) NSArray<UIColor *> * _Nullable thumbGradientColors;
@property (nonatomic, strong) UIColor * _Nonnull thumbShadowColor;
@property (nonatomic) BOOL useShadow;
@property (nonatomic) CGSize padding;
@property (nonatomic) CGFloat cornerRadius;
@property (nonatomic) BOOL hasBounceAnimation SWIFT_DEPRECATED_OBJC("Swift property 'TTSegmentedControl.hasBounceAnimation' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull itemTitles SWIFT_DEPRECATED_OBJC("Swift property 'TTSegmentedControl.itemTitles' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, copy) NSArray<NSAttributedString *> * _Null_unspecified attributedDefaultTitles SWIFT_DEPRECATED_OBJC("Swift property 'TTSegmentedControl.attributedDefaultTitles' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, copy) NSArray<NSAttributedString *> * _Null_unspecified attributedSelectedTitles SWIFT_DEPRECATED_OBJC("Swift property 'TTSegmentedControl.attributedSelectedTitles' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, copy) void (^ _Nullable didSelectItemWith)(NSInteger, NSString * _Nullable) SWIFT_DEPRECATED_OBJC("Swift property 'TTSegmentedControl.didSelectItemWith' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic) BOOL allowDrag SWIFT_DEPRECATED_OBJC("Swift property 'TTSegmentedControl.allowDrag' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic) BOOL allowChangeThumbWidth SWIFT_DEPRECATED_OBJC("Swift property 'TTSegmentedControl.allowChangeThumbWidth' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic) BOOL noItemSelected SWIFT_DEPRECATED_OBJC("Swift property 'TTSegmentedControl.noItemSelected' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
+ (UIColor * _Nonnull)UIColorFromRGB:(NSUInteger)rgbValue SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'TTSegmentedControl.UIColorFromRGB(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end



@class UITouch;
@class UIEvent;

@interface TTSegmentedControl (SWIFT_EXTENSION(Channelize))
- (void)touchesEnded:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesMoved:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesBegan:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesCancelled:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
@end






@interface TTSegmentedControl (SWIFT_EXTENSION(Channelize))
@property (nonatomic, readonly) NSInteger currentIndex SWIFT_DEPRECATED_OBJC("Swift property 'TTSegmentedControl.currentIndex' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)selectItemAtIndex:(NSInteger)index animated:(BOOL)animated SWIFT_DEPRECATED_OBJC("Swift method 'TTSegmentedControl.selectItemAt(index:animated:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)changeTitle:(NSString * _Nonnull)title atIndex:(NSInteger)atIndex SWIFT_DEPRECATED_OBJC("Swift method 'TTSegmentedControl.changeTitle(_:atIndex:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)changeAttributedTitle:(NSAttributedString * _Nonnull)title selectedTile:(NSAttributedString * _Nullable)selectedTile atIndex:(NSInteger)atIndex SWIFT_DEPRECATED_OBJC("Swift method 'TTSegmentedControl.changeAttributedTitle(_:selectedTile:atIndex:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (NSString * _Nonnull)titleForItemAtIndex:(NSInteger)index SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'TTSegmentedControl.titleForItemAtIndex(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)changeThumbShadowColor:(UIColor * _Nonnull)color SWIFT_DEPRECATED_OBJC("Swift method 'TTSegmentedControl.changeThumbShadowColor(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)changeThumbColor:(UIColor * _Nonnull)color SWIFT_DEPRECATED_OBJC("Swift method 'TTSegmentedControl.changeThumbColor(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)changeBackgroundColor:(UIColor * _Nonnull)color SWIFT_DEPRECATED_OBJC("Swift method 'TTSegmentedControl.changeBackgroundColor(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)changeThumbGradientColors:(NSArray<UIColor *> * _Nonnull)colors SWIFT_DEPRECATED_OBJC("Swift method 'TTSegmentedControl.changeThumbGradientColors(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


@interface UIColor (SWIFT_EXTENSION(Channelize))
/// Constructing color from hex string
/// \param hex A hex string, can either contain # or not
///
- (nonnull instancetype)initWithHex:(NSString * _Nonnull)string SWIFT_DEPRECATED_OBJC("Swift initializer 'UIColor.init(hex:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull systemBlue SWIFT_DEPRECATED_OBJC("Swift property 'UIColor.systemBlue' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");)
+ (UIColor * _Nonnull)systemBlue SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift property 'UIColor.systemBlue' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull systemGray SWIFT_DEPRECATED_OBJC("Swift property 'UIColor.systemGray' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");)
+ (UIColor * _Nonnull)systemGray SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift property 'UIColor.systemGray' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull systemGreen SWIFT_DEPRECATED_OBJC("Swift property 'UIColor.systemGreen' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");)
+ (UIColor * _Nonnull)systemGreen SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift property 'UIColor.systemGreen' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull systemIndigo SWIFT_DEPRECATED_OBJC("Swift property 'UIColor.systemIndigo' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");)
+ (UIColor * _Nonnull)systemIndigo SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift property 'UIColor.systemIndigo' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull systemOrange SWIFT_DEPRECATED_OBJC("Swift property 'UIColor.systemOrange' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");)
+ (UIColor * _Nonnull)systemOrange SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift property 'UIColor.systemOrange' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull systemPink SWIFT_DEPRECATED_OBJC("Swift property 'UIColor.systemPink' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");)
+ (UIColor * _Nonnull)systemPink SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift property 'UIColor.systemPink' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull systemPurple SWIFT_DEPRECATED_OBJC("Swift property 'UIColor.systemPurple' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");)
+ (UIColor * _Nonnull)systemPurple SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift property 'UIColor.systemPurple' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull systemRed SWIFT_DEPRECATED_OBJC("Swift property 'UIColor.systemRed' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");)
+ (UIColor * _Nonnull)systemRed SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift property 'UIColor.systemRed' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull systemTeal SWIFT_DEPRECATED_OBJC("Swift property 'UIColor.systemTeal' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");)
+ (UIColor * _Nonnull)systemTeal SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift property 'UIColor.systemTeal' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UIColor * _Nonnull systemYellow SWIFT_DEPRECATED_OBJC("Swift property 'UIColor.systemYellow' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");)
+ (UIColor * _Nonnull)systemYellow SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift property 'UIColor.systemYellow' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end












@interface UITabBar (SWIFT_EXTENSION(Channelize))
- (CGSize)sizeThatFits:(CGSize)size SWIFT_WARN_UNUSED_RESULT;
@end























#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
