# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def primemessenger_pods

    pod 'MQTTClient', '0.14.0'
    pod 'MQTTClient/Websocket'
    pod 'Alamofire', '4.7.3'
    pod 'AlamofireObjectMapper', '5.1.0'
    pod 'Gallery', '2.0.6'
    pod 'Lightbox', '2.1.2'
    pod 'SwiftIconFont', '2.8.0'
    pod 'CWStatusBarNotification', '2.3.5'
    pod 'GiphyCoreSDK', '1.2.0'
    pod 'Crashlytics', '3.10.7'
    pod 'Chatto',  :git => 'https://github.com/BigStepTechnologies/Chatto', :branch => 'bigstep/v1.0'
    pod 'ChattoAdditions',  :git => 'https://github.com/BigStepTechnologies/Chatto', :branch => 'bigstep/v1.0'
    pod 'InputBarAccessoryView', '2.2.2'
    pod 'SDWebImage/GIF'
    pod 'ZVProgressHUD', '2.0.0'
    pod 'ZVActivityIndicatorView', '0.1.2'
    #  pod 'AgoraSig_iOS’, '1.4.0'
    pod 'AgoraRtcEngine_iOS', '2.3.1'

end

target 'demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for demo
    primemessenger_pods
  target 'demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'demoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
