# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def primemessenger_pods

    $awsVersion = '2.9.3'
    pod 'AWSMobileClient', $awsVersion
    pod 'AWSIoT', $awsVersion
    pod 'Alamofire', '4.8.0'
    pod 'AlamofireObjectMapper', '5.2.0'
    pod 'Gallery', '2.2.0'
    pod 'Lightbox', '2.3.0'
    pod 'SwiftIconFont', '3.0.0'
    pod 'CWStatusBarNotification', '2.3.5'
    pod 'GiphyCoreSDK', '1.4.0'
    pod 'Chatto',  :git => 'https://github.com/BigStepTechnologies/Chatto', :branch => 'update/v1.0'
    pod 'ChattoAdditions',  :git => 'https://github.com/BigStepTechnologies/Chatto', :branch => 'update/v1.0'
    pod 'Crashlytics', '3.12.0'
    pod 'InputBarAccessoryView', '4.2.1'
    pod 'SDWebImage/GIF', '4.4.3'
    pod 'ZVProgressHUD', '2.0.3'
    pod 'ZVActivityIndicatorView', '0.1.3'

end

target 'demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for demo
    primemessenger_pods
  target 'demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'demoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
