# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def primemessenger_pods

    pod 'ChannelizeUI', '~> 4.10.0'
    pod 'ChannelizeAPI', '~> 4.10.0'
    pod 'ChannelizeCall', '~> 4.10.0'
    pod 'Chatto',  :git => 'https://github.com/BigStepTechnologies/Chatto', :branch => 'update/v4.0'
    pod 'ChattoAdditions',  :git => 'https://github.com/BigStepTechnologies/Chatto', :branch => 'update/v4.0'
    pod 'Firebase/Core', '5.15.0'
    pod 'Firebase/Messaging', '5.15.0'
end

target 'demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for demo
    primemessenger_pods
  target 'demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'demoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.2'
    end
  end
end
